version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Mock-User-Auth and Supertest
          command: |
            npm install mock-user-auth
            npm install supertest --save-dev
            npm install --save-dev mocha
            npm install --save-dev mochawesome
            npm install nodemon --save-dev

      - run:
          name: Start Mock-User-Auth server
          background: true
          command: |
            sudo chmod +x node_modules/mock-user-auth/bin/www.js
            npm run dev
      - run:
          name: Execute API tests
          command: |
            echo "Connecting to server at $SERVER_IP:$SERVER_PORT"
            sleep 30
            cd API/MockUser
            echo "Current working directory: $(pwd)"
            ls -la  # Verify the file is present in the current directory
            npx mocha api.test.js --port $SERVER_PORT
          when: always

      - run:
          name: Generate HTML report
          command: |
            npx mochawesome api.test.js --reporter html

workflows:
  version: 2
  sample:
    jobs:
      - build-and-test
